[tool.poetry]
name = "de4l-detour-privacy-metric"
version = "0.0.1"
description = "A package for estimating the exposure of private information in trajectory data."
repository = "https://git.informatik.uni-leipzig.de/scads/de4l/privacy/de4l-detour-privacy-metric"
authors = ["Maja Schneider","Lukas Gehrke"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pandas = "^1.3.4"
geopy = "^2.2.0"
urllib3 = "^1.26.7"
torch = { version = "~1.9.0", optional = true }
de4l_geodata = { git = "git+ssh://git@git.informatik.uni-leipzig.de/scads/de4l/privacy/de4l-geodata.git", rev = "3e4b8bb62db3d39fb4651723e3ee61e8e5c22735" }

[tool.poetry.extras]
torch = ["torch"]

[tool.poetry.urls]
"Bug Tracker" = "https://git.informatik.uni-leipzig.de/scads/de4l/privacy/de4l-detour-privacy-metric/-/issues"
"Source" = "https://git.informatik.uni-leipzig.de/scads/de4l/privacy/de4l-detour-privacy-metric"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
